# TCL File Generated by Component Editor 17.1
# Sun Apr 01 17:16:09 MSK 2018
# DO NOT MODIFY


# 
# Avalon_MM_byteorder_changer "Avalon_MM_byteorder_changer" v1.0
#  2018.04.01.17:16:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Avalon_MM_byteorder_changer
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avalon_MM_byteorder_changer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Avalon_MM_byteorder_changer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL am_ch_byteorder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file am_ch_byteorder.sv SYSTEM_VERILOG PATH am_ch_byteorder.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 64
set_parameter_property DATA_WIDTH DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter BURST_WIDTH INTEGER 8
set_parameter_property BURST_WIDTH DEFAULT_VALUE 8
set_parameter_property BURST_WIDTH DISPLAY_NAME BURST_WIDTH
set_parameter_property BURST_WIDTH TYPE INTEGER
set_parameter_property BURST_WIDTH UNITS None
set_parameter_property BURST_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BURST_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point slv
# 
add_interface slv avalon end
set_interface_property slv addressUnits SYMBOLS
set_interface_property slv associatedClock clock_sink
set_interface_property slv associatedReset reset_sink
set_interface_property slv bitsPerSymbol 8
set_interface_property slv burstOnBurstBoundariesOnly false
set_interface_property slv burstcountUnits WORDS
set_interface_property slv explicitAddressSpan 0
set_interface_property slv holdTime 0
set_interface_property slv linewrapBursts false
set_interface_property slv maximumPendingReadTransactions 1
set_interface_property slv maximumPendingWriteTransactions 0
set_interface_property slv readLatency 0
set_interface_property slv readWaitTime 1
set_interface_property slv setupTime 0
set_interface_property slv timingUnits Cycles
set_interface_property slv writeWaitTime 0
set_interface_property slv ENABLED true
set_interface_property slv EXPORT_OF ""
set_interface_property slv PORT_NAME_MAP ""
set_interface_property slv CMSIS_SVD_VARIABLES ""
set_interface_property slv SVD_ADDRESS_GROUP ""

add_interface_port slv slv_writedata writedata Input DATA_WIDTH
add_interface_port slv slv_write write Input 1
add_interface_port slv slv_readdata_valid readdatavalid Output 1
add_interface_port slv slv_read read Input 1
add_interface_port slv slv_waitrequest waitrequest Output 1
add_interface_port slv slv_address address Input ADDR_WIDTH
add_interface_port slv slv_burstcount burstcount Input BURST_WIDTH
add_interface_port slv slv_byteenable byteenable Input DATA_WIDTH/8
add_interface_port slv slv_readdata readdata Output DATA_WIDTH
set_interface_assignment slv embeddedsw.configuration.isFlash 0
set_interface_assignment slv embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slv embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slv embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point mst
# 
add_interface mst avalon start
set_interface_property mst addressUnits SYMBOLS
set_interface_property mst associatedClock clock_sink
set_interface_property mst associatedReset reset_sink
set_interface_property mst bitsPerSymbol 8
set_interface_property mst burstOnBurstBoundariesOnly false
set_interface_property mst burstcountUnits WORDS
set_interface_property mst doStreamReads false
set_interface_property mst doStreamWrites false
set_interface_property mst holdTime 0
set_interface_property mst linewrapBursts false
set_interface_property mst maximumPendingReadTransactions 0
set_interface_property mst maximumPendingWriteTransactions 0
set_interface_property mst readLatency 0
set_interface_property mst readWaitTime 1
set_interface_property mst setupTime 0
set_interface_property mst timingUnits Cycles
set_interface_property mst writeWaitTime 0
set_interface_property mst ENABLED true
set_interface_property mst EXPORT_OF ""
set_interface_property mst PORT_NAME_MAP ""
set_interface_property mst CMSIS_SVD_VARIABLES ""
set_interface_property mst SVD_ADDRESS_GROUP ""

add_interface_port mst mst_write write Output 1
add_interface_port mst mst_readdata readdata Input DATA_WIDTH
add_interface_port mst mst_readdata_valid readdatavalid Input 1
add_interface_port mst mst_read read Output 1
add_interface_port mst mst_waitrequest waitrequest Input 1
add_interface_port mst mst_address address Output ADDR_WIDTH
add_interface_port mst mst_burstcount burstcount Output BURST_WIDTH
add_interface_port mst mst_byteenable byteenable Output DATA_WIDTH/8
add_interface_port mst mst_writedata writedata Output DATA_WIDTH

