# TCL File Generated by Component Editor 16.1
# Sun Apr 29 12:58:40 MSK 2018
# DO NOT MODIFY


# 
# HLS_CTL "HLS_CTL" v1.0
#  2018.04.29.12:58:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module HLS_CTL
# 
set_module_property DESCRIPTION ""
set_module_property NAME HLS_CTL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME HLS_CTL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hls_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hls_ctl.sv SYSTEM_VERILOG PATH hls_ctl.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_source
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ptr_o data Output 64


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point slv0
# 
add_interface slv0 avalon end
set_interface_property slv0 addressUnits WORDS
set_interface_property slv0 associatedClock clock_sink
set_interface_property slv0 associatedReset reset_sink
set_interface_property slv0 bitsPerSymbol 8
set_interface_property slv0 burstOnBurstBoundariesOnly false
set_interface_property slv0 burstcountUnits WORDS
set_interface_property slv0 explicitAddressSpan 0
set_interface_property slv0 holdTime 0
set_interface_property slv0 linewrapBursts false
set_interface_property slv0 maximumPendingReadTransactions 1
set_interface_property slv0 maximumPendingWriteTransactions 0
set_interface_property slv0 readLatency 0
set_interface_property slv0 readWaitTime 1
set_interface_property slv0 setupTime 0
set_interface_property slv0 timingUnits Cycles
set_interface_property slv0 writeWaitTime 0
set_interface_property slv0 ENABLED true
set_interface_property slv0 EXPORT_OF ""
set_interface_property slv0 PORT_NAME_MAP ""
set_interface_property slv0 CMSIS_SVD_VARIABLES ""
set_interface_property slv0 SVD_ADDRESS_GROUP ""

add_interface_port slv0 slv0_writedata writedata Input 32
add_interface_port slv0 slv0_write write Input 1
add_interface_port slv0 slv0_readdata readdata Output 32
add_interface_port slv0 slv0_readdata_valid readdatavalid Output 1
add_interface_port slv0 slv0_read read Input 1
add_interface_port slv0 slv0_waitrequest waitrequest Output 1
add_interface_port slv0 slv0_address address Input 1
set_interface_assignment slv0 embeddedsw.configuration.isFlash 0
set_interface_assignment slv0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slv0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slv0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point slv1
# 
add_interface slv1 avalon end
set_interface_property slv1 addressUnits WORDS
set_interface_property slv1 associatedClock clock_sink
set_interface_property slv1 associatedReset reset_source
set_interface_property slv1 bitsPerSymbol 8
set_interface_property slv1 burstOnBurstBoundariesOnly false
set_interface_property slv1 burstcountUnits WORDS
set_interface_property slv1 explicitAddressSpan 0
set_interface_property slv1 holdTime 0
set_interface_property slv1 linewrapBursts false
set_interface_property slv1 maximumPendingReadTransactions 0
set_interface_property slv1 maximumPendingWriteTransactions 0
set_interface_property slv1 readLatency 1
set_interface_property slv1 readWaitStates 0
set_interface_property slv1 readWaitTime 0
set_interface_property slv1 setupTime 0
set_interface_property slv1 timingUnits Cycles
set_interface_property slv1 writeWaitTime 0
set_interface_property slv1 ENABLED true
set_interface_property slv1 EXPORT_OF ""
set_interface_property slv1 PORT_NAME_MAP ""
set_interface_property slv1 CMSIS_SVD_VARIABLES ""
set_interface_property slv1 SVD_ADDRESS_GROUP ""

add_interface_port slv1 slv1_writedata writedata Input 64
add_interface_port slv1 slv1_write write Input 1
set_interface_assignment slv1 embeddedsw.configuration.isFlash 0
set_interface_assignment slv1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slv1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slv1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock ""
set_interface_property reset_source associatedDirectReset reset_sink
set_interface_property reset_source associatedResetSinks reset_sink
set_interface_property reset_source synchronousEdges NONE
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source rst_o reset Output 1

