# TCL File Generated by Component Editor 17.1
# Sun Apr 01 18:34:58 MSK 2018
# DO NOT MODIFY


# 
# HLS_CTL "HLS_CTL" v1.0
#  2018.04.01.18:34:58
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module HLS_CTL
# 
set_module_property DESCRIPTION ""
set_module_property NAME HLS_CTL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME HLS_CTL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hls_ctl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hls_ctl.sv SYSTEM_VERILOG PATH hls_ctl.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point slv
# 
add_interface slv avalon end
set_interface_property slv addressUnits WORDS
set_interface_property slv associatedClock clock_sink
set_interface_property slv associatedReset reset_sink
set_interface_property slv bitsPerSymbol 8
set_interface_property slv burstOnBurstBoundariesOnly false
set_interface_property slv burstcountUnits WORDS
set_interface_property slv explicitAddressSpan 0
set_interface_property slv holdTime 0
set_interface_property slv linewrapBursts false
set_interface_property slv maximumPendingReadTransactions 1
set_interface_property slv maximumPendingWriteTransactions 0
set_interface_property slv readLatency 0
set_interface_property slv readWaitTime 1
set_interface_property slv setupTime 0
set_interface_property slv timingUnits Cycles
set_interface_property slv writeWaitTime 0
set_interface_property slv ENABLED true
set_interface_property slv EXPORT_OF ""
set_interface_property slv PORT_NAME_MAP ""
set_interface_property slv CMSIS_SVD_VARIABLES ""
set_interface_property slv SVD_ADDRESS_GROUP ""

add_interface_port slv slv_writedata writedata Input 32
add_interface_port slv slv_write write Input 1
add_interface_port slv slv_readdata readdata Output 32
add_interface_port slv slv_readdata_valid readdatavalid Output 1
add_interface_port slv slv_read read Input 1
add_interface_port slv slv_waitrequest waitrequest Output 1
set_interface_assignment slv embeddedsw.configuration.isFlash 0
set_interface_assignment slv embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slv embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slv embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset reset_sink
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ptr_o data Output 64


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1

