# TCL File Generated by Component Editor 16.1
# Mon Apr 23 19:59:22 MSK 2018
# DO NOT MODIFY


# 
# shared_irq "Shared IRQ Sender" v1.0
#  2018.04.23.19:59:22
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module shared_irq
# 
set_module_property DESCRIPTION ""
set_module_property NAME shared_irq
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP IRQ
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Shared IRQ Sender"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL shared_irq
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file shared_irq.sv SYSTEM_VERILOG PATH shared_irq.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point interrupt_receiver_1
# 
add_interface interrupt_receiver_1 interrupt start
set_interface_property interrupt_receiver_1 associatedAddressablePoint ""
set_interface_property interrupt_receiver_1 associatedClock clock_sink
set_interface_property interrupt_receiver_1 irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver_1 ENABLED true
set_interface_property interrupt_receiver_1 EXPORT_OF ""
set_interface_property interrupt_receiver_1 PORT_NAME_MAP ""
set_interface_property interrupt_receiver_1 CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver_1 SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver_1 irq1_i irq Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq_o irq Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_i reset Input 1


# 
# connection point interrupt_receiver_0
# 
add_interface interrupt_receiver_0 interrupt start
set_interface_property interrupt_receiver_0 associatedAddressablePoint ""
set_interface_property interrupt_receiver_0 associatedClock clock_sink
set_interface_property interrupt_receiver_0 associatedReset reset_sink
set_interface_property interrupt_receiver_0 irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver_0 ENABLED true
set_interface_property interrupt_receiver_0 EXPORT_OF ""
set_interface_property interrupt_receiver_0 PORT_NAME_MAP ""
set_interface_property interrupt_receiver_0 CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver_0 SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver_0 irq0_i irq Input 1

