# TCL File Generated by Component Editor 17.0
# Sun Apr 15 17:11:51 MSK 2018
# DO NOT MODIFY


# 
# rd_dma "Avalon-MM Read Simple DMA" v1.0
# mt 2018.04.15.17:11:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rd_dma
# 
set_module_property DESCRIPTION ""
set_module_property NAME rd_dma
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Memory
set_module_property AUTHOR mt
set_module_property DISPLAY_NAME "Avalon-MM Read Simple DMA"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rd_dma
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file rd_dma.sv SYSTEM_VERILOG PATH ../rtl/rd_dma.sv TOP_LEVEL_FILE
add_fileset_file rd_dma_regs_pkg.sv SYSTEM_VERILOG PATH ../rtl/rd_dma_regs_pkg.sv
add_fileset_file sc_fifo.qip OTHER PATH ../rtl/sc_fifo.qip
add_fileset_file sc_fifo.sv SYSTEM_VERILOG PATH ../rtl/sc_fifo.sv


# 
# parameters
# 
add_parameter AMM_DMA_DATA_W INTEGER 64 ""
set_parameter_property AMM_DMA_DATA_W DEFAULT_VALUE 64
set_parameter_property AMM_DMA_DATA_W DISPLAY_NAME AMM_DMA_DATA_W
set_parameter_property AMM_DMA_DATA_W WIDTH ""
set_parameter_property AMM_DMA_DATA_W TYPE INTEGER
set_parameter_property AMM_DMA_DATA_W UNITS None
set_parameter_property AMM_DMA_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_DMA_DATA_W DESCRIPTION ""
set_parameter_property AMM_DMA_DATA_W HDL_PARAMETER true
add_parameter AMM_DMA_ADDR_W INTEGER 32 ""
set_parameter_property AMM_DMA_ADDR_W DEFAULT_VALUE 32
set_parameter_property AMM_DMA_ADDR_W DISPLAY_NAME AMM_DMA_ADDR_W
set_parameter_property AMM_DMA_ADDR_W WIDTH ""
set_parameter_property AMM_DMA_ADDR_W TYPE INTEGER
set_parameter_property AMM_DMA_ADDR_W UNITS None
set_parameter_property AMM_DMA_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_DMA_ADDR_W DESCRIPTION ""
set_parameter_property AMM_DMA_ADDR_W HDL_PARAMETER true
add_parameter AMM_CSR_DATA_W INTEGER 32 ""
set_parameter_property AMM_CSR_DATA_W DEFAULT_VALUE 32
set_parameter_property AMM_CSR_DATA_W DISPLAY_NAME AMM_CSR_DATA_W
set_parameter_property AMM_CSR_DATA_W WIDTH ""
set_parameter_property AMM_CSR_DATA_W TYPE INTEGER
set_parameter_property AMM_CSR_DATA_W UNITS None
set_parameter_property AMM_CSR_DATA_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_CSR_DATA_W DESCRIPTION ""
set_parameter_property AMM_CSR_DATA_W HDL_PARAMETER true
add_parameter AMM_CSR_ADDR_W INTEGER 4 ""
set_parameter_property AMM_CSR_ADDR_W DEFAULT_VALUE 4
set_parameter_property AMM_CSR_ADDR_W DISPLAY_NAME AMM_CSR_ADDR_W
set_parameter_property AMM_CSR_ADDR_W WIDTH ""
set_parameter_property AMM_CSR_ADDR_W TYPE INTEGER
set_parameter_property AMM_CSR_ADDR_W UNITS None
set_parameter_property AMM_CSR_ADDR_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AMM_CSR_ADDR_W DESCRIPTION ""
set_parameter_property AMM_CSR_ADDR_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point amm_slave_csr
# 
add_interface amm_slave_csr avalon end
set_interface_property amm_slave_csr addressUnits WORDS
set_interface_property amm_slave_csr associatedClock clock_sink
set_interface_property amm_slave_csr associatedReset reset_sink
set_interface_property amm_slave_csr bitsPerSymbol 8
set_interface_property amm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property amm_slave_csr burstcountUnits WORDS
set_interface_property amm_slave_csr explicitAddressSpan 0
set_interface_property amm_slave_csr holdTime 0
set_interface_property amm_slave_csr linewrapBursts false
set_interface_property amm_slave_csr maximumPendingReadTransactions 0
set_interface_property amm_slave_csr maximumPendingWriteTransactions 0
set_interface_property amm_slave_csr readLatency 0
set_interface_property amm_slave_csr readWaitTime 1
set_interface_property amm_slave_csr setupTime 0
set_interface_property amm_slave_csr timingUnits Cycles
set_interface_property amm_slave_csr writeWaitTime 0
set_interface_property amm_slave_csr ENABLED true
set_interface_property amm_slave_csr EXPORT_OF ""
set_interface_property amm_slave_csr PORT_NAME_MAP ""
set_interface_property amm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property amm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port amm_slave_csr amm_slave_csr_address_i address Input AMM_CSR_ADDR_W
add_interface_port amm_slave_csr amm_slave_csr_read_i read Input 1
add_interface_port amm_slave_csr amm_slave_csr_readdata_o readdata Output AMM_CSR_DATA_W
add_interface_port amm_slave_csr amm_slave_csr_write_i write Input 1
add_interface_port amm_slave_csr amm_slave_csr_writedata_i writedata Input AMM_CSR_DATA_W
set_interface_assignment amm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment amm_slave_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ast_source
# 
add_interface ast_source avalon_streaming start
set_interface_property ast_source dataBitsPerSymbol 8
set_interface_property ast_source errorDescriptor ""
set_interface_property ast_source firstSymbolInHighOrderBits true
set_interface_property ast_source maxChannel 0
set_interface_property ast_source readyLatency 0
set_interface_property ast_source ENABLED true
set_interface_property ast_source EXPORT_OF ""
set_interface_property ast_source PORT_NAME_MAP ""
set_interface_property ast_source CMSIS_SVD_VARIABLES ""
set_interface_property ast_source SVD_ADDRESS_GROUP ""

add_interface_port ast_source ast_source_endofpacket_o endofpacket Output 1
add_interface_port ast_source ast_source_data_o data Output AMM_DMA_DATA_W
add_interface_port ast_source ast_source_empty_o empty Output 3
add_interface_port ast_source ast_source_ready_i ready Input 1
add_interface_port ast_source ast_source_startofpacket_o startofpacket Output 1
add_interface_port ast_source ast_source_valid_o valid Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink srst_i reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock ""
set_interface_property avalon_master associatedReset ""
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master amm_dma_address_o address Output AMM_DMA_ADDR_W
add_interface_port avalon_master amm_dma_read_o read Output 1
add_interface_port avalon_master amm_dma_readdata_i readdata Input AMM_DMA_DATA_W
add_interface_port avalon_master amm_dma_readdata_valid_i readdatavalid Input 1
add_interface_port avalon_master amm_dma_waitreques_i waitrequest Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender end_irq_o irq Output 1

